apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: web-namespace
spec:
  type: NodePort
  selector:
    app: employees
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000