apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-app-replicaset
  namespace: web-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: web-app-container
        image: 104387388648.dkr.ecr.us-east-1.amazonaws.com/assignment2-webapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "10.244.0.5"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "rootpassword"
